<?php

/**
 * @file
 * Views date exposed filter main.
 * http://drupal.stackexchange.com/questions/26376/where-can-i-learn-about-how-to-create-a-custom-exposed-filter-for-views-3-and-d7
 */

/**
 * Implements hook_views_api().
 */
function date_exp_filter_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'date_exp_filter') . '/inc',
  );
}

/**
 * Implements hook_views_data().
 */
function date_exp_filter_views_data() {
  $data = array();

  $data['views']['date_changed'] = array(
  'group' => t('Custom'),
    'title' => t('Changed date filter.'),
    'help' => t('Filters by changed date.'),
    'filter' => array(
      'path' => drupal_get_path('module', 'date_exp_filter') . '/inc',
      'handler' => 'date_exp_filter_handler_filter_changed',
    )
  );

  return $data;
}
